################################################################################
# Runs checks and install on all PRs as well as branch pushes except "main".
################################################################################
name: continuous_integration

# place "magic strings" used in the workflow here for convenient maintenance
env:
  # this variable is used to compare against forked repositories
  OUR_REPO: "ourchitecture/ourchitecture.github.com"

on:
  push:
    branches: ["*", "!main"]
  pull_request:
    branches: ["*"]

jobs:
  integration:
    if: ${{ github.repository == env.OUR_REPO }}

    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # See: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: "yarn"
          cache-dependency-path: "./**/yarn.lock"

      - name: install
        run: |
          make install
