# This is a basic workflow to help you get started with Actions
name: DevOps

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    integration:

        env:
            CI: true

        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                # See: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
                cache: 'yarn'
                cache-dependency-path: './**/yarn.lock'
            
            - name: install
              run: |
                make install
                sudo chown -R $(whoami) ./docs
            
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              if: ${{ github.event_name == 'push' }}
              with:
                title: "docs: auto-generated documentation"
                signoff: true
                commit-message: "docs: auto-generated documentation [skip ci]"
                body: "Automatically generated documentation that requires a PR, because the main branch is protected."
                labels: "documentation"
                reviewers: "ericis"
                assignees: "ericis"
